apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springbootrestapp
  title: springbootrestapp
  annotations:
    github.com/project-slug: springbootrestapp/springbootrestapp
  tags:
    - spring-boot
    - java
    - maven
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: springbootrestapptemplate
  namespace: default
spec:
  type: service
  owner: user:guest
  path: .
  definition: ./template.yaml

